### Get all
GET http://localhost:3000/api/users

### Get single
GET http://localhost:3000/api/users/1

### Create new
POST http://localhost:3000/api/users
Content-Type: application/json; charset=utf-8

{
  "username": "Coolguy",
  "password": "am8w7d7N",
  "id": "1"
}

### UPDATE
PUT http://localhost:3000/api/users/5
Content-Type: application/json; charset=utf-8

{
    "username": "WaO",
    "password": "waw125",
    "id": "328"
}

### DELETE
DELETE http://localhost:3000/api/users/5
