### Get all
GET http://localhost:3000/api/users

### Get single
GET http://localhost:3000/api/users/1

### Create new User
POST http://localhost:3000/api/users
Content-Type: application/json; charset=utf-8

{
  "email": "jakob@jh.com",
  "password": "qwertyuiQ1!"
}

### Create new Message
POST http://localhost:3000/api/msg
Content-Type: application/json; charset=utf-8

{
  "userid": "7",
  "message": "Hejsan"
}

### UPDATE
PUT http://localhost:3000/api/users/5
Content-Type: application/json; charset=utf-8

{
    "username": "WaO",
    "password": "waw125",
    "id": "328"
}

### DELETE
DELETE http://localhost:3000/api/users/5
